---
name: JSON

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  style:
    name: Check JSON style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prettier
        uses: creyD/prettier_action@v4.4
        with:
          dry: true
          prettier_options: "--check **/*.json"
