---
name: Markdown

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Markdown files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.4.0
        with:
          files: "**.md"

  style:
    name: Check Markdown style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prettier
        uses: creyD/prettier_action@v4.6
        with:
          dry: true
          prettier_options: "--check **/*.md"
