---
name: Rust

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  lint:
    name: Lint Rust code
    runs-on: ubuntu-latest

    steps:
      - name: Install Just
        run: sudo snap install --edge --classic just

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache build artifacts
        uses: swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: cargo-1.96.1

      - name: Cache compilation artifacts
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

      - name: Run Clippy
        run: just lint

  style:
    name: Check Rust style
    runs-on: ubuntu-latest

    steps:
      - name: Install Just
        run: sudo snap install --edge --classic just

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Rustfmt
        run: just format --check

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Just
        run: sudo snap install --edge --classic just

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache build artifacts
        uses: swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: cargo-1.96.1

      - name: Cache compilation artifacts
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

      - name: Run tests
        run: just test
