---
name: YAML

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: actionshub/yamllint@v1.8.3

  style:
    name: Check YAML style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prettier
        uses: creyD/prettier_action@v4.4
        with:
          dry: true
          prettier_options: "--check **/*.{yml,yaml}"
